use charity_app_db;
INSERT INTO Charities (title, descript, goal) VALUES ("Pay my rent please", "i am once again asking for your financial support",500.00);
INSERT INTO Charities (title, descript, goal) VALUES ("the knicks suck", "help fund the knicks to get better players", 3000000.00);
INSERT INTO Charities (title, descript, goal) VALUES ("My hearthstone cards are ancient", "Please help me to climb the ranked ladder with new cards", 150.00);
INSERT INTO Charities (title, descript, goal) VALUES ("also need better cards in hearthstone", "i dont want to play battlegrounds anymore", 100.00);
INSERT INTO users (username, passwd, first_name, last_name) VALUES ("maxken512", "test", "Max", "Kennedy");
INSERT INTO users (username, passwd, first_name, last_name) VALUES ("Anierva95", "test1", "Anthony", "Nierva");
INSERT INTO users (username, passwd, first_name, last_name) VALUES ("Henryni914", "test2", "Henry", "Ni");
INSERT INTO users (username, passwd, first_name, last_name) VALUES ("ZhaoyangXia0204", "test3", "Zhaoyang", "Xia");
INSERT INTO Charities (title, descript, goal, UserId) VALUES ("also need better cards in hearthstone", "i dont want to play battleg anymore", 110.00, 1);
INSERT INTO Transactions (amount, CharityId) VALUES (100, 5);